### ISSUE TITLE
osquery_queries/win_forensics/win_forensics_outlook_security_disabled.yaml

### ISSUE THREAD

**Issue by johnosn** [Cisco-Talos/osquery_queries#1]
osquery_queries/win_forensics/win_forensics_outlook_security_disabled.yaml

The osquery schema for registry does not have a field called "value" as indicated in the WHERE clause.

**Comment by cmarczewski** [comment]
Fix has been committed via dccbf9804de1dc9698c6d89e913d4c047c748f1d.

Thanks for reporting this.
