### ISSUE TITLE
malware_raccoon_filepath query fails

### ISSUE THREAD

**Issue by johnosn** [Cisco-Talos/osquery_queries#12]
malware_raccoon_filepath query fails with the message:
	W0406 16:52:06.023344 22284 virtual_table.cpp:963] Table file was queried without a required column in the WHERE clause
	W0406 16:52:06.023344 22284 virtual_table.cpp:974] Please see the table documentation: https://osquery.io/schema/#file
	Error: constraint failed

A Query like the one below would be able to return results.

```
WITH ud AS (
	SELECT directory || '\AppData\LocalLow' AS directory
	FROM users
	WHERE directory LIKE "%\Users\%"
)
SELECT
	f.path,
	f.directory,
	f.filename,
	h.sha256,
	f.uid,
	f.gid,
	f.mode,
	f.size,
	DATETIME(f.atime, "unixepoch","UTC") AS last_access_time,
	DATETIME(f.mtime, "unixepoch", "UTC") AS last_modified,
	DATETIME(f.ctime, "unixepoch", "UTC") AS last_status_change_time,
	DATETIME(f.btime, "unixepoch", "UTC") AS creation_time,
	f.type
FROM ud
	JOIN file f ON ud.directory = f.directory
	LEFT JOIN hash h ON f.path = h.path 
WHERE LENGTH(f.filename) = 16;
```

**Comment by cmarczewski** [comment]
Resolved via 7f0a59e06ad63097fe69790320ad80aaaf5b4258.

Thank you for bringing this to our attention.
