### ISSUE TITLE
osquery_queries/win_malware/win_malware_hafnium_cmds.yaml not executing

### ISSUE THREAD

**Issue by johnosn** [Cisco-Talos/osquery_queries#16]
Quotes used in the query statement are not accepted and return the following error message when executed in Cisco Orbital.

![win_malware_hafnium_cmds](https://user-images.githubusercontent.com/24979537/115914496-042f4100-a440-11eb-8c99-68a520fb7df2.png)

Current Query Statement
```
query: '"SELECT p.name, p.pid, DATETIME(p.start_time, ''unixepoch'', ''UTC'') AS
start_time, p.cmdline FROM processes p WHERE p.parent = (SELECT pid FROM processes
WHERE name LIKE "w3wp%") AND p.cmdline LIKE "cmd /c %&echo [E]"; " '
```

Working Query Statement
```
query: "SELECT p.name, p.pid, DATETIME(p.start_time, 'unixepoch', 'UTC') AS start_time,
p.cmdline FROM processes p WHERE p.parent = (SELECT pid FROM processes WHERE name 
LIKE 'w3wp%') AND p.cmdline LIKE 'cmd /c %&echo [E]'; "
```

**Comment by cmarczewski** [comment]
Resolved via adc0742305ee440dbcc9eb8468a80b1882200ee2.

Thank you for opening the issue.
