### ISSUE TITLE
osquery_queries/win_malware/malware_poetrat_filepath.json

### ISSUE THREAD

**Issue by johnosn** [Cisco-Talos/osquery_queries#3]
Each LIKE value in the WHERE clause should be surrounded by single quotes.

		"query": "SELECT f.path, f.filename, h.sha256, f.uid, f.gid, f.mode, f.size, DATETIME(f.atime, 'unixepoch','UTC') AS last_access_time, DATETIME(f.mtime, 'unixepoch', 'UTC') AS last_modified, DATETIME(f.ctime, 'unixepoch', 'UTC') AS last_status_change_time, DATETIME(f.btime, 'unixepoch', 'UTC') AS creation_time, f.type FROM file f LEFT JOIN hash h ON f.path=h.path WHERE (f.path LIKE '%\\Python37\\smile_funs.py' OR f.path LIKE '%\\Python37\\frown.py' OR f.path LIKE '%\\Python37\\smile.py' OR f.path LIKE '%Users\\Public\\Milan%\\config.lua' OR f.path LIKE '%Users\\Public\\Mew\\%pythonw.exe'); ",

**Comment by cmarczewski** [comment]
Hi Adam.

Thank you for bringing this to our attention. We resolved this issue via 7e0d107d606a42ad430d5f9678b08d03ffbcc20a.
