### ISSUE TITLE
osquery_queries/win_malware/malware_lodarat_filepath.yaml

### ISSUE THREAD

**Issue by johnosn** [Cisco-Talos/osquery_queries#4]
Use double quotes instead of two single quotes in the queries  WHERE clause

`  query: 'SELECT f.path, f.directory, f.filename, h.sha256, f.uid, f.gid, f.mode,
    f.size, DATETIME(f.atime, "unixepoch","UTC")  AS last_access_time, DATETIME(f.mtime,
    "unixepoch", "UTC")  AS last_modified, DATETIME(f.ctime, "unixepoch", "UTC")  AS
    last_status_change_time, DATETIME(f.btime, "unixepoch", "UTC")  AS creation_time  FROM
    file f JOIN hash h ON f.path=h.path  WHERE f.path LIKE "C:\Users\%\AppData\Roaming\Windata\%.exe";
    AND f.filename LIKE regex_match(f.filename, "([a-zA-Z]{6}|svchost)\.exe", 0); '`

**Comment by cmarczewski** [comment]
Hi Adam.

Thank you for bringing this to our attention. We resolved this issue via 7e0d107d606a42ad430d5f9678b08d03ffbcc20a.
