### ISSUE TITLE
Queries using the file table without specifying path or directory

### ISSUE THREAD

**Issue by johnosn** [Cisco-Talos/osquery_queries#7]
The following queries under '.\win_malware\' use the osquery file table, but do not specify a required value for either the 'path' or 'directory' fields per the [osquery file specification](https://github.com/osquery/osquery/blob/master/specs/utility/file.table).

* malware_arcane_filepath_detected.yaml
* ransomware_mespinoza_filepath.yaml
* ransomware_mountlocker_filepath.yaml
* malware_inveighzero_filepath.yaml
* ransomware_lockbit_filepath.yaml

**Comment by cmarczewski** [comment]
Hi Adam.

It appears that specification is only for ingesting or inserting data and is not needed for osquery data retrieval. This issue will be closed with no further action. Thanks.

**Comment by johnosn** [comment]
The following queries still all fail with the message "constraint failed" when executed by osquery 4.4.0 that comes with Cisco Orbital.
* malware_inveighzero_filepath
* ransomware_buran_filepath
* ransomware_conti_filepath
* ransomware_lockbit_filepath
* ransomware_mespinoza_filepath
* ransomware_mountlocker_filepath
* ransomware_pay2key_filepath
![malware_inveighzero_filepath](https://user-images.githubusercontent.com/24979537/115913144-363fa380-a43e-11eb-882f-4b1bb8af32c9.png)
![ransomware_buran_filepath](https://user-images.githubusercontent.com/24979537/115913147-38a1fd80-a43e-11eb-9887-1a59bdcfa600.png)
![ransomware_conti_filepath](https://user-images.githubusercontent.com/24979537/115913155-3b045780-a43e-11eb-80b0-764087dda627.png)
![ransomware_lockbit_filepath](https://user-images.githubusercontent.com/24979537/115913163-3d66b180-a43e-11eb-916f-20513efce731.png)
![ransomware_mespinoza_filepath](https://user-images.githubusercontent.com/24979537/115913169-40fa3880-a43e-11eb-8463-ff5d77d25b94.png)
![ransomware_mountlocker_filepath](https://user-images.githubusercontent.com/24979537/115913179-435c9280-a43e-11eb-9779-1d62d506efa5.png)
![ransomware_pay2key_filepath](https://user-images.githubusercontent.com/24979537/115913187-45265600-a43e-11eb-90e9-576d4127ab1d.png)

**Comment by cmarczewski** [comment]
Resolved via 8c605a8e37bfaf3ff4a1b95dac507f43e4ea7f3f.

Thanks for reopening the issue.
